### ISSUE TITLE
Crash when single-play as second player

### ISSUE THREAD

**Issue by ghost** [MidflightDigital/ddrsn3-theme#11]
The game crashes when playing alone on the second player's (right) side.
It happens when selecting the play mode (not play style).
[crashinfo.txt](https://github.com/MidflightDigital/ddrsn3-theme/files/1059474/crashinfo.txt)

**Comment by tertu-m** [comment]
Does it work in OpenGL mode?

**Comment by ghost** [comment]
Nope, it got the same result.
[crashinfo.txt](https://github.com/MidflightDigital/ddrsn3-theme/files/1059631/crashinfo.txt)
Here's the log file (in case there isn't enough info)
[log.txt](https://github.com/MidflightDigital/ddrsn3-theme/files/1059630/log.txt)

**Comment by tertu-m** [comment]
I'll see if we can get you a build with debugging info, because there really isn't enough here for me to determine what's happening. It looks like this might be a StepMania core bug, unless you can't get it to happen in default.

**Comment by ghost** [comment]
Also, I noticed something: 
![2017-06-09_165617](https://user-images.githubusercontent.com/29264400/26994254-da00494e-4d34-11e7-853a-a712b005a920.jpg)
The glowing edges are on the top-left corner.
I realized that I can access standard mode on the second player side, but if I change the play mode, it crashes.

**Comment by tertu-m** [comment]
Okay, hmm. I'll do more investigatikn

**Comment by tertu-m** [comment]
Here's a crashlog from a version of SM with symbols. I'm not sure exactly why it crashes, but it appears that the choice isn't getting set for Player 2 for some reason.
[crashinfo.txt](https://github.com/MidflightDigital/ddrsn3-theme/files/1110184/crashinfo.txt)

**Comment by tertu-m** [comment]
@GeForceMSX98 we appear to have hit an obscure bug in StepMania. the next release will have a workaround. In the mean time, if you change `ShowCursor` in metrics.ini under `ScreenSelectPlayMode` to `false`, it doesn't crash.

**Comment by tertu-m** [comment]
fixed in b93df22
