### ISSUE TITLE
Add missing speed mods

### ISSUE THREAD

**Issue by ghost** [MidflightDigital/ddrsn3-theme#13]
Just like the title says, add 1.75x, 4x, 4.5x, 5.5x, 6x, 6.5x, 7x, 7.5x and 8x. I've been struggling to MA songs that required 4x and 4.5x.

**Comment by tertu-m** [comment]
We're going to add support for custom speed mods soon (the Data/SpeedMods.txt thing).

**Comment by tertu-m** [comment]
I'm sorry, I lost motivation. I'll do it today.

**Comment by tertu-m** [comment]
9f54c32 doesn't exactly fix this but provides you with the means to override it should you so desire, which is as far as we're going to go with this directly.

**Comment by tertu-m** [comment]
just FYI we did end up adding these to the default speed mod list in r7.0
