### ISSUE TITLE
enhancement, BGM and Shared Background For DDR A, A20, A20 PLUS, A3, and DDR WORLD

### ISSUE THREAD

**Issue by ChrisNolan202020202** [MidflightDigital/ddrsn3-theme#22]
please

**Comment by ChrisNolan202020202** [comment]
add milestone r8

**Comment by Inorizushi** [comment]
With all respect, the theme hasn't been updated in 6 years. It is effectively dead and we have zero plans to update it besides possibly adding patches for outfox support.
