### ISSUE TITLE
Cleared Screen Slow?

### ISSUE THREAD

**Issue by matthewwithanm** [MidflightDigital/ddrsn3-theme#4]
This theme is amazing! Thanks so much!!

My only nitpick is that I've noticed that the scores take a really long time to display. I feel like I'm waiting at the cleared screen for quite a while. Is this a KP?

**Comment by tertu-m** [comment]
I haven't experienced unusually long delays. Does it play the cleared animation and just sit there for a bit? (It might just be SM loading things back into memory and taking a while to do that.)

**Comment by tertu-m** [comment]
@matthewwithanm is this worse than with default?

**Comment by matthewwithanm** [comment]
Yeah, definitely. But I stopped using the theme 😬

**Comment by tertu-m** [comment]
darn. anyways, there are a lot of places where our performance isn't as good as it could be so i'll keep looking into this

**Comment by tertu-m** [comment]
i have no leads to go on here so i'm just closing this.
